---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/companies":
    get:
      summary: list companies
      responses:
        '200':
          description: successful
    post:
      summary: create company
      responses:
        '200':
          description: successful
  "/api/v1/companies/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show company
      responses:
        '200':
          description: successful
    patch:
      summary: update company
      responses:
        '200':
          description: successful
    put:
      summary: update company
      responses:
        '200':
          description: successful
    delete:
      summary: delete company
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
